name: Scheduled API Task

on:
  schedule:
    - cron: '* * * * *' # Every minute
#  workflow_dispatch: # Manual trigger for testing

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          python3 my_script.py
