name: Cron Test

on:
  schedule:
    - cron: '* * * * *' # every minute
#  workflow_dispatch: # manual trigger

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say time and trigger source
        run: |
          echo "Current time: $(date)"
          echo "Triggered by: ${{ github.event_name }}"
