name: Scheduled API Task

on:
  schedule:
    - cron: '* * * * *' # Every minute
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Install OpenAI client
        run: pip install openai

      - name: Run Python script with headers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ELIIS_CSRF_TOKEN: ${{ secrets.ELIIS_CSRF_TOKEN }}
        run: python3 my_script.py
#comment
